/*
const REQUIRED_STATION_ID = "00:00:00:00:00:00";

const TWILIO_SERVICE_ID = "";
const TWILIO_ACCOUNT_ID = "";
const TWILIO_AUTH_TOKEN = "";

const PROD_ZAP_DATA_FOLDER_ID = "";
const TEST_ZAP_DATA_FOLDER_ID = "";

const GREEN_GEAR_RECIP = "";
*/